# Generated by Django 4.1.4 on 2022-12-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registered_people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Mobile', models.IntegerField()),
                ('Email', models.EmailField(max_length=30)),
                ('Course', models.CharField(max_length=20)),
                ('Source', models.CharField(max_length=20)),
                ('LeadStatus', models.CharField(max_length=20)),
                ('DemoDate', models.DateField()),
                ('Counsler', models.CharField(max_length=20)),
                ('Remarks', models.CharField(max_length=20)),
            ],
        ),
    ]
