# Generated by Django 4.1.4 on 2022-12-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='joining_people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Course', models.CharField(max_length=20)),
                ('DateOfJoining', models.DateField()),
                ('DateOfCompletion', models.DateField()),
                ('CourseFee', models.IntegerField()),
                ('Instructor', models.CharField(max_length=20)),
                ('AadharNo', models.IntegerField()),
                ('Email', models.EmailField(max_length=30)),
                ('Mobile', models.IntegerField()),
                ('Remarks', models.CharField(max_length=20)),
            ],
        ),
    ]
