# Generated by Django 4.1.4 on 2022-12-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_joining_people_aadharno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joining_people',
            name='AadharNo',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='joining_people',
            name='CourseFee',
            field=models.IntegerField(default=''),
        ),
    ]
