# Generated by Django 4.1.4 on 2022-12-21 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_joining_people_aadharno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joining_people',
            name='AadharNo',
        ),
        migrations.RemoveField(
            model_name='joining_people',
            name='CourseFee',
        ),
    ]
